### ISSUE TITLE
Support for tables

### ISSUE THREAD

**Issue by fruitcoder** [DoccZz/DocCArchive#6] opened 2022-01-08 17:51 UTC
Thanks for your amazing work. My documentation almost works with docc2html except for tables. I've seen that the `Content` enum currently doesn't support tables and wanted to ask how hard it is to implement. Maybe I could create a PR if you could point me in the right direction :) 

My table in the json file looks like this
```
{
  "type": "table",
  "rows": [
    [
      [
        {
          "type": "paragraph",
          "inlineContent": [
            {
              "type": "text",
              "text": "Mode"
            }
          ]
        }
      ],
      [
        {
          "type": "paragraph",
          "inlineContent": [
            {
              "type": "text",
              "text": "Description"
            }
          ]
        }
      ]
    ],
    [
      [
        {
          "type": "paragraph",
          "inlineContent": [
            {
              "type": "codeVoice",
              "code": "buffering"
            }
          ]
        }
      ],
      [
        {
          "type": "paragraph",
          "inlineContent": [
            {
              "type": "text",
              "text": "The mode indicates a buffering state."
            }
          ]
        }
      ]
    ],
    [
      [
        {
          "type": "paragraph",
          "inlineContent": [
            {
              "type": "codeVoice",
              "code": "pause"
            }
          ]
        }
      ],
      [
        {
          "type": "paragraph",
          "inlineContent": [
            {
              "type": "text",
              "text": "The mode indicates a button tap triggers pause (two vertical bars)."
            }
          ]
        }
      ]
    ],
    [
      [
        {
          "type": "paragraph",
          "inlineContent": [
            {
              "type": "codeVoice",
              "code": "play"
            }
          ]
        }
      ],
      [
        {
          "type": "paragraph",
          "inlineContent": [
            {
              "type": "text",
              "text": "The mode indicates a button tap triggers play (triangle)."
            }
          ]
        }
      ]
    ],
    [
      [
        {
          "type": "paragraph",
          "inlineContent": [
            {
              "type": "codeVoice",
              "code": "stop"
            }
          ]
        }
      ],
      [
        {
          "type": "paragraph",
          "inlineContent": [
            {
              "type": "text",
              "text": "The mode indicates a button tap triggers stop (square)."
            }
          ]
        }
      ]
    ]
  ],
  "header": "row"
},
{
  "anchor": "Respond-to-Button-Taps",
  "level": 2,
  "type": "heading",
  "text": "Respond to Button Taps"
},
```

**Comment by helje5** [comment] 2022-01-08 19:39
An example DocCArchive which reproduces that would be helpful.

**Comment by fruitcoder** [comment] 2022-01-08 20:26
Will post tomorrow 👍🏻

**Comment by fruitcoder** [comment] 2022-01-09 11:12
[TableDocC.zip](https://github.com/DoccZz/DocCArchive/files/7834916/TableDocC.zip)

**Comment by helje5** [comment] 2022-01-09 11:36
The export of that doesn't seem to carry any table? Looks like I can get it, if I put the table into the comment of the struct.

**Comment by fruitcoder** [comment] 2022-01-09 11:48
Just noticed it, sorry. I don't get why the DocC catalog seems to be ignored completely (I used the one from my project and just deleted everything that's unnecessary).

**Comment by helje5** [comment] 2022-01-09 13:08
OK, should be fixed.

**Closed as completed by helje5** 2022-01-09 13:08 UTC
